### ISSUE TITLE
Some tiles are slightly off coordinates (grey lines in dirt)

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/otoch#12]
![lines](https://user-images.githubusercontent.com/67130/52108230-33c1bb00-2634-11e9-81a7-a02fefc6d2a1.png)

**Comment by chr15m** [comment]
@retrogradeorbit noted:

 * Grass edge tiles have lines still.
 * Ladder tile has bleed from tile above.

**Comment by chr15m** [comment]
@retrogradeorbit is this fixed for you?

**Comment by retrogradeorbit** [comment]
yes fixed
