### ISSUE TITLE
implement titlescreen

### ISSUE THREAD

**Issue by retrogradeorbit** [retrogradeorbit/otoch#8]

**Comment by retrogradeorbit** [comment]
@chr15m check out the new titlescreen. I've deployed it. I used scale to size the graphics, but Im imagining them as full resolution.

What do you think?

Im not sure if the wiggle is good, or if it would be better moving some other way (maybe an infinite right to left scroll with a walking character?)

If you approve, then I need the assets rendered higher res. The scales are:

Banana tree: 4x (512 x 512)
Pyramid and player: 2x (128 x 128 + 128 x 128 = 128 x 256)
Ground: 2x (presently laid out as tiles... not sure how to do this... maybe leave it as scaled tiles for now?)

**Comment by chr15m** [comment]
Looks awesome!

**Comment by chr15m** [comment]
@retrogradeorbit can I export the full tileset at 4x in `tilesx4.png` and then you can scale them down?

**Comment by chr15m** [comment]
@retrogradeorbit let me know if `tiles-title.png` looks ok on that branch.

**Comment by retrogradeorbit** [comment]
That looks spot on

**Comment by retrogradeorbit** [comment]
https://retrogradeorbit.github.io/otoch/

more issues.

1. theres an overlap between the tree and the left-top dirt tile.
2. there needs to be a few middle layer dirt tiles

**Comment by chr15m** [comment]
@retrogradeorbit I assumed it would be possible to take a 4 x 3 tile - is that not possible? They have to be exact squares?

What do you mean by middle layer dirt tiles?

**Comment by retrogradeorbit** [comment]
@chr15m I can make a 4x3 tile of the banana tree but even then there is either the top of the tree cut off, or a slight overlap. 

![overlap](https://user-images.githubusercontent.com/265500/52157847-62d83b00-26cd-11e9-9137-2e37e5e81857.png)

By middle dirt tiles I mean dirt tiles that have nothing on them, no grass on top, nor no jaggies underneath.

**Comment by chr15m** [comment]
@retrogradeorbit will fix.

**Comment by chr15m** [comment]
@retrogradeorbit try now.

**Comment by retrogradeorbit** [comment]
layout looks better but there are some thin grey lines again.

**Comment by retrogradeorbit** [comment]
the grey lines are very subtle. I don't think they  matter. The titlescreen looks fine with this tileset. I'm going to close the ticket.
